
#ifndef _IFD_SPARROW_H_
#define _IFD_SPARROW_H_

#include "sparrow.h"
//#include "source.h"
#include "reg_def.h"
#include "tuner\tuner.h"
#include "timer_event.h"
#include "rosprintf.h"
#include "video\video.h"
#include "flow_struct.h"
#include "scaler_idomain\syncproc.h"
#include "scaler_idomain\measure.h"
#include "reg_def.h"
#include "flow_scaler.h"
#include "mode.h"
#include "mode_customer.h"


#ifndef UINT8
#define UINT8	unsigned char
#endif

#ifndef UINT16
#define UINT16	unsigned int
#endif

#ifndef UINT32
#define UINT32	unsigned long
#endif

#define __FUNCTION__ " "
#define IFD_LOG_LEVEL LOGGER_INFO
#define IFD_CODE code
#define IFD_XDATA xdata
#define CONFIG_SPARROW

#define IFD_CHIP_VER_A()      ((rtdf_inl(SYS_VER_0x2db1) == 0x0) ? _TRUE : _FALSE)
#define IFD_CHIP_VER()      (rtdf_inl(SYS_VER_0x2db1))
#define SLRTIMER_IFD_AGC_VAR 0
#define ifd_set_agc_variance_on_active timerevent_atv_ifd_chk_agc_var
#define ifd_set_agc_variance_on_cancel timerevent_atv_ifd_chk_agc_var
#define IFD_ScalerTimer_CancelTimerEvent(event) fw_timer_event_CancelTimerEvent(event)
#define IFD_ReactiveTimerEvent(flag, ms, event) fw_timer_event_ActiveTimerEvent(ms, event)

#define ScalerTimer_DelayXms(ms) fw_timer_event_DelayXms((UINT16)ms)

#define	_Tuner_MAX_NO			1//CONFIG_Tuner_Max_NUMBER


#ifdef CONFIG_IFD_DRVIF_DEBUG_MSG
#define IFD_CALLER() RTD_Log(LOGGER_INFO,"");
#define IFD_FACTORY_LOG RTD_Log
#define IFD_DEBUG_MSG RTD_Log
#ifdef CONFIG_IFD_DRV_DEBUG_MSG
#define IFD_DRV_DEBUG_MSG RTD_Log
#else
#define IFD_DRV_DEBUG_MSG //
#endif
#else
#define IFD_DEBUG_MSG RTD_Log
#define IFD_DRV_DEBUG_MSG //
#define IFD_FACTORY_LOG //
#endif

typedef enum _IFD_SIG_MODE
{
    _SIG_MODE_AUTO=0,
    _SIG_MODE_PAL,
    _SIG_MODE_NTSC,
    _SIG_MODE_NTSC_443,
    _SIG_MODE_SECAM,
    _SIG_MODE_PAL_DK,
    _SIG_MODE_PAL_I,
    _SIG_MODE_PAL_BG,
    _SIG_MODE_SECAM_DK,
    _SIG_MODE_SECAM_L,
    _SIG_MODE_SECAM_LA,
    _SIG_MODE_MAX,
} IFD_SIG_MODE;

typedef enum _IFD_SIG_MODE_AUDIO
{
    _SIG_MODE_AUDIO_DK      ,
    _SIG_MODE_AUDIO_I       ,
    _SIG_MODE_AUDIO_BG      ,
    _SIG_MODE_AUDIO_MN      ,
    _SIG_MODE_AUDIO_L       ,
    _SIG_MODE_AUDIO_SCANNTSC,
    _SIG_MODE_AUDIO_SCANPAL ,
} IFD_SIG_MODE_AUDIO;

typedef enum _TUNER_ID
{
    TUNER_NULL = 0,
    TUNER_XUGUANG_TDQ6K_T116CW,
    TUNER_ALPS_TDAG4_D01A,
    TUNER_LG_TDTC_G29D,
    TUNER_KEH_FTDC3S20V04,
    TUNER_XUGUANG_TDQ_6FT_W116H,
    TUNER_XUGUANG_TDQ_6ID_GW115HR,
    TUNER_XUGUANG_HFT8B_115CW,
    TUNER_XUGUANG_DVT_8ADC1_T41F0HS,
    TUNER_CHANGHONG_DTI1_E4I12VH,
    TUNER_ALPS_TDAU3XD01A,
    TUNER_TUNER_TCL_F17CT_2DA_E,
    TUNER_TCL_F41CT_2_E,
    TUNER_TCL_F13WP_2DP_E,
    TUNER_XUGUANG_TDQ_6PD_LW115CWADC,
} TUNER_ID;

//system
#define SYSTEM_PLL27X_VADDR SYS_PLL_27X_0_0x2c64
//vd regiser
#define VDC_INOUT_CTRL_VADDR	VDC_INOUT_CTRL_0x5018
#define VDC_AGC_GATE_TH_SWAP_VADDR	VDC_AGC_GATE_TH_SWAP_0x508c
#define VDC_AVOUT_FIFO_STATUS_VADDR VDC_AVOUT_FIFO_STATUS_0x501c
#define VDC_AGC_DGAIN_STATUS2_VADDR VDC_AGC_DGAIN_STATUS2_0x5260
#define VDC_AGC_DGAIN_STATUS1_VADDR VDC_AGC_DGAIN_STATUS1_0x5264
//ifd register address
#define IFD_CR_BPF_SEL_VADDR        CR_BPF_SEL_0x5c00
#define IFD_CR_BPF_READ_VADDR       CR_BPF_READ_0x5c04
#define IFD_CR_PGAIN_VADDR      CR_PGAIN_0x5c08
#define IFD_CR_LOCK_VADDR       CR_LOCK_0x5c0c
#define IFD_CR_NCO_FIX_DATA_VADDR       CR_NCO_FIX_DATA_0x5c10
#define IFD_CR_FREQ_SAT_VADDR       CR_FREQ_SAT_0x5c14
#define IFD_CR_FREQ_STATUS_VADDR    CR_FREQ_STATUS_0x5c18
#define IFD_CR_WEIGHT_EN_VADDR      CR_WEIGHT_EN_0x5c1c
#define IFD_CR_PHASE_BAD_VADDR      CR_PHASE_BAD_0x5c20
#define IFD_VCLAMP_IN_MAX_SAT_VADDR     VCLAMP_IN_MAX_SAT_0x5c24
#define IFD_VCLAMP_IN_MIN_SAT_VADDR     VCLAMP_IN_MIN_SAT_0x5c28
#define IFD_DUMMY1_VADDR        DUMMY1_0x5c2c
#define IFD_DUMMY2_VADDR        DUMMY2_0x5c30
#define IFD_DUMMY3_VADDR        DUMMY3_0x5c34
#define IFD_DUMMY4_VADDR        DUMMY4_0x5c38
#define IFD_DUMMY5_VADDR        DUMMY5_0x5c3c
#define IFD_SHAPE_FILTER_SELECTION_VADDR    SHAPE_FILTER_SELECTION_0x5c40
#define IFD_DEC_FIFO_STATUS_VADDR       DEC_FIFO_STATUS_0x5c44
#define IFD_SOFT_RESET_27_CLK_PHASE_VADDR   SOFT_RESET_27_CLK_PHASE_0x5c48
#define IFD_DMA_VADDR       DMA_0x5c4c
#define IFD_CR_ERR_THD_VADDR        CR_ERR_THD_0x5c50
#define IFD_CR_AUTO_RESET_EN_VADDR      CR_AUTO_RESET_EN_0x5c54
#define IFD_CR_PHASE_INVERSE_VADDR      CR_PHASE_INVERSE_0x5c58
#define IFD_CR_WBLF_CNTL_VADDR      CR_WBLF_CNTL_0x5c60
#define IFD_CR_WBLF_TH_VADDR        CR_WBLF_TH_0x5c64
#define IFD_CR_PHASE_ERR_CAL_VADDR      CR_PHASE_ERR_CAL_0x5c68
#define IFD_CR_VARIANCE_DEBOUNCE_VADDR      CR_VARIANCE_DEBOUNCE_0x5c6c
#define IFD_EQ_FILTER_SEL_VADDR     EQ_FILTER_SEL_0x5c70
#define IFD_EQ_FILTER_READ_VADDR    EQ_FILTER_READ_0x5c74
#define IFD_VIDEO_BW_SEL_VADDR      VIDEO_BW_SEL_0x5c80
#define IFD_GRP_DELAY_EN_VADDR      GRP_DELAY_EN_0x5c84
#define IFD_GRP_DELAY_READ_VADDR    GRP_DELAY_READ_0x5c88
#define IFD_CLAMPING_SCALE_VADDR    CLAMPING_SCALE_0x5c8c
#define IFD_CLAMPING_THR_MAX_VADDR      CLAMPING_THR_MAX_0x5c90
#define IFD_CLAMPING_THR_MIN_VADDR      CLAMPING_THR_MIN_0x5c94
#define IFD_OFFSET_VADDR        OFFSET_0x5c98
#define IFD_RESAMPLER_STATUS_VADDR      RESAMPLER_STATUS_0x5c9c
#define IFD_AUDIO_BP_SEL_VADDR      AUDIO_BP_SEL_0x5cc0
#define IFD_AUDIO_GAIN_MANU_VADDR       AUDIO_GAIN_MANU_0x5cc4
#define IFD_AUDIO_GAIN_STATUS_VADDR     AUDIO_GAIN_STATUS_0x5cc8
#define IFD_AGC_ENABLE_SEL_VADDR    AGC_ENABLE_SEL_0x5d00
#define IFD_AGC_MAX_LIMIT_CNT_1_VADDR   AGC_MAX_LIMIT_CNT_1_0x5d04
#define IFD_AGC_MAX_COUNT_FOR_COARSE_MODE_AGC_CNTL1_VADDR AGC_MAX_COUNT_FOR_COARSE_MODE_AGC_CNTL1_0x5d08
#define IFD_AGC_MAX_COUNT_FOR_FINELOCK_MODE_AGC_CNTL2_VADDR AGC_MAX_COUNT_FOR_FINELOCK_MODE_AGC_CNTL2_0x5d0c
#define IFD_AGC_AVG_TARGET_VADDR    AGC_AVG_TARGET_0x5d10
#define IFD_AGC_MAX_COUNT_FOR_COARSE_MODE_AGC_LOCK2_VADDR AGC_MAX_COUNT_FOR_COARSE_MODE_AGC_LOCK2_0x5d14
#define IFD_AGC_TARG_VAL_VADDR      AGC_TARG_VAL_0x5d18
#define IFD_AGC_CNTL_SEL_VADDR      AGC_CNTL_SEL_0x5d1c
#define IFD_AGC_MANU_VALUE_VADDR    AGC_MANU_VALUE_0x5d20
#define IFD_AGC_IF_MANU_VALUE_VADDR     AGC_IF_MANU_VALUE_0x5d24
#define IFD_AGC_RF_MANU_VALUE_VADDR     AGC_RF_MANU_VALUE_0x5d28
#define IFD_KI_VAL_VADDR        KI_VAL_0x5d2c
#define IFD_IF_AGC_MIN_VADDR        IF_AGC_MIN_0x5d30
#define IFD_RF_AGC_LIMIT_VALUE_VADDR    RF_AGC_LIMIT_VALUE_0x5d34
#define IFD_AGC_LOCK_LEN_VADDR      AGC_LOCK_LEN_0x5d38
#define IFD_AGC_LOCK_TH_VADDR       AGC_LOCK_TH_0x5d3c
#define IFD_AGC_LOCK_STATUS_VADDR       AGC_LOCK_STATUS_0x5d40
#define IFD_AGC_HSYNC_START_VADDR       AGC_HSYNC_START_0x5d44
#define IFD_AGC_VSYNC_START1_VADDR      AGC_VSYNC_START1_0x5d48
#define IFD_AGC_PEAK_DETECT_VADDR       AGC_PEAK_DETECT_0x5d50
#define IFD_AGC_PEAK_VALUE_VADDR    AGC_PEAK_VALUE_0x5d54
#define IFD_AGC_SIGMA_DELTA_LPF_VADDR   AGC_SIGMA_DELTA_LPF_0x5d58
#define IFD_AGC_MAX_STATUS_VADDR    AGC_MAX_STATUS_0x5d5c
#define IFD_AGC_ERR0_STATUS_VADDR       AGC_ERR0_STATUS_0x5d60
#define IFD_AGC_ACC3_STATUS_VADDR       AGC_ACC3_STATUS_0x5d64
#define IFD_AGC_IF_STATUS_VADDR     AGC_IF_STATUS_0x5d68
#define IFD_AGC_RF_STATUS_VADDR     AGC_RF_STATUS_0x5d6c
#define IFD_AGC_PGA_1_VADDR     AGC_PGA_1_0x5d70
#define IFD_AGC_MASK_THR_VADDR      AGC_MASK_THR_0x5d74
#define IFD_AGC_PGA_13B_CTL1_VADDR      AGC_PGA_13B_CTL1_0x5d78
#define IFD_VTOP_VALUE_VADDR        VTOP_VALUE_0x5d80
#define IFD_KRF_VALUE_VADDR     KRF_VALUE_0x5d84
#define IFD_READ_PGA_VADDR      READ_PGA_0x5d88
#define IFD_NOISE_CAL_VADDR     NOISE_CAL_0x5d8c
#define IFD_AGC_ORIGINAL_SEL_VADDR      AGC_ORIGINAL_SEL_0x5d90
#define IFD_AGC_PGA_CNTL_VADDR      AGC_PGA_CNTL_0x5d94
#define IFD_AGC_LINEBASE_CTL_VADDR      AGC_LINEBASE_CTL_0x5d98
#define IFD_AGC_MAX2_CNT_1_VADDR    AGC_MAX2_CNT_1_0x5d9c
#define IFD_AGC_IN_KP_KI_VADDR      AGC_IN_KP_KI_0x5da0
#define IFD_AGC_IN_MAX_MIN_VADDR    AGC_IN_MAX_MIN_0x5da4
#define IFD_AGC_TARG_VAL_LOOP2_VADDR    AGC_TARG_VAL_LOOP2_0x5da8
#define IFD_AGC_MAX2_LIMIT_CNT_1_VADDR      AGC_MAX2_LIMIT_CNT_1_0x5dac
#define IFD_AGC_LOOOP2_ERR_VADDR    AGC_LOOOP2_ERR_0x5db0
#define IFD_AGC_INNER_STATUS_VADDR      AGC_INNER_STATUS_0x5db4
#define IFD_LOOP2_KP_KI_ERR_VADDR       LOOP2_KP_KI_ERR_0x5db8
#define IFD_AGC_MAX2_IN_OUT_VADDR       AGC_MAX2_IN_OUT_0x5dbc
#define IFD_AGC_PEAK2_DETECT_VADDR      AGC_PEAK2_DETECT_0x5dc0
#define IFD_AGC_PEAK2_VALUE_VADDR       AGC_PEAK2_VALUE_0x5dc4
#define IFD_AGC_PEAK2_STATUS_VADDR      AGC_PEAK2_STATUS_0x5dc8
#define IFD_AGC_LOCK2_TH_VADDR      AGC_LOCK2_TH_0x5dcc
#define IFD_AGC_LOOP2_CNTL_VADDR    AGC_LOOP2_CNTL_0x5dd0
#define IFD_SIGMA_DELTA_CNTL_VADDR      SIGMA_DELTA_CNTL_0x5dd4
#define IFD_AGC_INTERRUPT_THD_VADDR     AGC_INTERRUPT_THD_0x5dd8
#define IFD_AGC_2STEP_EN_VADDR      AGC_2STEP_EN_0x5ddc
#define IFD_AGC_DGAIN_STEP_VADDR    AGC_DGAIN_STEP_0x5de0
#define IFD_AGC_DGAIN_THR_VADDR     AGC_DGAIN_THR_0x5de4
#define IFD_AGC_DGAIN_TO_PGA_VADDR      AGC_DGAIN_TO_PGA_0x5de8
#define IFD_AGC_DGAIN_VIRTUAL_PGA_HSYNC_GATE_VADDR  AGC_DGAIN_VIRTUAL_PGA_HSYNC_GATE_0x5dec
#define IFD_INTERRUPT_MASK_EN_VADDR     INTERRUPT_MASK_EN_0x5df0
#define IFD_AGC_FINE_TUNE_DOWN_SAMPLE_VADDR     AGC_FINE_TUNE_DOWN_SAMPLE_0x5df4
#define IFD_2STEP_AGC_STATUS_VADDR      IFD_2STEP_AGC_STATUS_0x5df8
#define IFD_DEBUG_MODE_VADDR        DEBUG_MODE_0x5f40
#define IFD_DEBUG_MODE2_VADDR       DEBUG_MODE2_0x5f44
#define IFD_TEST_MODE_VADDR     TEST_MODE_0x5f48
#define IFD_CR_SELF_TEST_VADDR      CR_SELF_TEST_0x5f4c
#define IFD_CRC_CTRL_REGISTER_VADDR     CRC_CTRL_REGISTER_0x5f50
#define IFD_CRC1_RESULT_VADDR       CRC1_RESULT_0x5f54
#define IFD_CRC2_RESULT_VADDR       CRC2_RESULT_0x5f58
#define IFD_DACTEST_REGISTER1_VADDR     DACTEST_REGISTER1_0x5f5c
#define IFD_AD_BYPASS_ENABLE_VADDR      AD_BYPASS_ENABLE_0x5f60
#define IFD_INPUT_FIFO_STATUS_VADDR     INPUT_FIFO_STATUS_0x5f64
#define IFD_INPUT_BYPASS_ENABLE_VADDR   INPUT_BYPASS_ENABLE_0x5f68
#define IFD_CP_TEST_ENABLE_VADDR    CP_TEST_ENABLE_0x5f6c
#define IFD_AGC_VIRTUAL_PGA_VADDR       AGC_VIRTUAL_PGA_0x5f70
#define IFD_AGC_VSYNC_START2_VADDR      AGC_VSYNC_START2_0x5f74
#define IFD_AGC_HSYNC_START2_VADDR      AGC_HSYNC_START2_0x5f78
#define IFD_FPGA_TEST1_VADDR        FPGA_TEST1_0x5f80
#define IFD_FPGA_TEST2_VADDR        FPGA_TEST2_0x5f84
#define IFD_FPGA_TEST3_VADDR        FPGA_TEST3_0x5f88
#define IFD_FPGA_TEST4_DEBUG_CLK_VADDR      FPGA_TEST4_DEBUG_CLK_0x5f8c
#define IFD_AIN_SEL_VADDR       AIN_SEL_0x5fc0
#define IFD_ADC_SHGAIN_VADDR        ADC_SHGAIN_0x5fc4
#define IFD_ADC_CMSEL_VADDR     ADC_CMSEL_0x5fc8
#define IFD_ADC_IFBW_VADDR      ADC_IFBW_0x5fcc
#define IFD_ADC_CK_VADDR        ADC_CK_0x5fd0
#define IFD_ADC_CKOUTDELAY_VADDR    ADC_CKOUTDELAY_0x5fd4
#define IFD_ADC_SVRT_VADDR      ADC_SVRT_0x5fd8
#define IFD_ADC_SVRB_VADDR      ADC_SVRB_0x5fdc
#define IFD_ADC_TOS_VADDR       ADC_TOS_0x5fe0
#define IFD_ADC_SIBMBIAS_VADDR      ADC_SIBMBIAS_0x5fe4
#define IFD_ADC_SIBIFPGA_VADDR      ADC_SIBIFPGA_0x5fe8
#define IFD_ADC_MBIASPOW_VADDR      ADC_MBIASPOW_0x5fec
#define IFD_ADC_IFPGAPOW_VADDR      ADC_IFPGAPOW_0x5ff0
#define IFD_ADC_ANALOG_RESERVE_VADDR    ADC_ANALOG_RESERVE_0x5ff4


//============================

UINT8 drv_ifd_Freq_Offset_Small(void);
#ifndef CONFIG_TUNER_SILICON

void drv_ifd_eq_en(bool enable);
bool drv_ifd_eq_en_get_info(void);
#endif
void timerevent_atv_ifd_chk_agc_var(void);
void  drv_ifd_set_cr_error_var_sel(bool sel);
void  drv_ifd_set_agc_cr_var_sel(bool sel);
void drv_ifd_cr_wblf_reset(bool enable);
#endif

