/*==========================================================================
  * Copyright (c)      Realtek Semiconductor Corporation, 2009
  * All rights reserved.
  * ========================================================================*/

/*================= File Description =======================================*/
/**
 * @file
 * 	This file is for rtdaccess related functions.
 *
 * @author 	$Author$
 * @date	$Date$
 * @version	$Revision$
 * @ingroup	rtdaccess
 */

/**
 * @addtogroup rtdaccess
 * @{
 */

#ifndef _PCB_CUSTOMER_H
#define _PCB_CUSTOMER_H
#include "autoconf.h"
#include "sparrow.h"
#include "pcb\pcb_conf_def.h"
#include "char\uart.h"
#include "char\lsadc.h"

// Pad Setting
#define PAD_PORTA
#define PAD_PORTA_7_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_7_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_7_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_7_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_7_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_6_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_6_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_6_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_6_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_6_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_5_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_5_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_5_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_5_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_5_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_4_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_4_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_4_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_4_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_4_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_3_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_3_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_3_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_3_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_3_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_2_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_2_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_2_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_2_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_2_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_1_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_1_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_1_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_1_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_1_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTA_0_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTA_0_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTA_0_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTA_0_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTA_0_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB
#define PAD_PORTB_7_SLEW_RATE				PAD_SLEW_RATE_SELECTION_FAST
#define PAD_PORTB_7_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_8mA
#define PAD_PORTB_7_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_7_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_7_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_6_SLEW_RATE				PAD_SLEW_RATE_SELECTION_FAST
#define PAD_PORTB_6_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_8mA
#define PAD_PORTB_6_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_6_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_6_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_5_SLEW_RATE				PAD_SLEW_RATE_SELECTION_FAST
#define PAD_PORTB_5_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_8mA
#define PAD_PORTB_5_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_5_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_5_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_4_SLEW_RATE				PAD_SLEW_RATE_SELECTION_FAST
#define PAD_PORTB_4_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_8mA
#define PAD_PORTB_4_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_4_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_4_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_3_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTB_3_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTB_3_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_3_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_3_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_2_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTB_2_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTB_2_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_2_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_2_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_1_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTB_1_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTB_1_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_1_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_1_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTB_0_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTB_0_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTB_0_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTB_0_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTB_0_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC
#define PAD_PORTC_7_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_7_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_7_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_7_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_7_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_6_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_6_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_6_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_6_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_6_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_5_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_5_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_5_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_5_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_5_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_4_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_4_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_4_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_4_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_4_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_3_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_3_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_3_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_3_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_3_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_2_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_2_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_2_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_2_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_2_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_1_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_1_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_1_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_1_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_1_SMITH_TRIGGER_CONTROL	_DISABLE

#define PAD_PORTC_0_SLEW_RATE				PAD_SLEW_RATE_SELECTION_SLOW
#define PAD_PORTC_0_DRIVING_STRENGTH		PAD_DRIVING_STRENGTH_SELECTION_4mA
#define PAD_PORTC_0_PULL_UP_CONTROL			PAD_INTERNAL_PULL_UP_CONTROL_DISABLE
#define PAD_PORTC_0_PULL_DOWN_CONTROL		PAD_INTERNAL_PULL_DOWN_CONTROL_DISABLE
#define PAD_PORTC_0_SMITH_TRIGGER_CONTROL	_DISABLE

// Pin Share configuration

//0: TCON13
//1: GPIOA[7]	[default]
//2: IRQ_OUT
//3: IRRX
//4: V8_DATA7
//5: XTAL_OUT
//6: IF_AGC
//7: Reserved
#define PIN_SHARE_PORTA_7						1

//0: GPIOA[6]
//1: GPIOA[6]	[default]
//2: TCON7
//3: IRQ_OUT
//4:V8_DATA6
//5: I2S_O_SCLK
//6: UART1_TX
//7: I2S_I_SCLK
#define PIN_SHARE_PORTA_6						1
//silicon Tuner
//0: GPIOA[5]
//1: GPIOA[5]	[default]
//2: TCON5
//3: IF_AGC
//4: V8_DATA5
//5: I2S_O_WS
//6: UART1_RX
//7: I2S_I_WS
#define PIN_SHARE_PORTA_5						1//3

//0: I2C_S_SCL
//1: GPIOA[4]	[default]
//2: TCON0
//3: XTAL_OUT
//4:V8_DATA4
//5: I2S_O_DATA2
//6: I2C_M1_SCL
//7: I2S_I_DATA2
#define PIN_SHARE_PORTA_4						1

//0: I2C_S_SDA
//1: GPIOA[3]	[default]
//2: TCON1
//3: SPDIFO
//4: V8_DATA3
//5: I2S_O_DATA1
//6: I2C_M1_SDA
//7: I2S_I_DATA1
#define PIN_SHARE_PORTA_3						1




#if 1//(CONFIG_DISPLAY_PANEL_STYLE == _PANEL_INTERFACE_TTL)
#define PIN_SHARE_PORTA_2						3//0: SPDIFI//1: GPIOA[2]	[default]// 2: TCON2// 3: TTL_DEN//4:V8_DATA2//4:V8_DATA2//5: I2S_O_DATA0//6: Reserved//7: I2S_I_DATA0
#define PIN_SHARE_PORTA_1						3//0: SPDIFO//1: GPIOA[1]	[default]//2: TCON3// 3: TTL_DVS//4: V8_DATA1//5: I2S_O_MCLK//6: Reserved//7: I2S_I_MCLK
#else
#define PIN_SHARE_PORTA_2						1//0: SPDIFI//1: GPIOA[2]	[default]// 2: TCON2// 3: TTL_DEN//4:V8_DATA2//4:V8_DATA2//5: I2S_O_DATA0//6: Reserved//7: I2S_I_DATA0
#define PIN_SHARE_PORTA_1						1//0: SPDIFO//1: GPIOA[1]	[default]//2: TCON3// 3: TTL_DVS//4: V8_DATA1//5: I2S_O_MCLK//6: Reserved//7: I2S_I_MCLK
#endif


//1: Reserved		[default]
//~7: Reserved
#define PIN_SHARE_PORTA_0						1

//Reserved
//#define PIN_SHARE_PORTA_0

//0: SPI_DO
//1: GPIOB[7]
//2~7: Reserved
#define PIN_SHARE_PORTB_7						0

//0: SPI_DI
//1: GPIOB[6]
//2~7: Reserved
#define PIN_SHARE_PORTB_6						0

//0: SPI_SCK
//1: GPIOB[5]
//2~7: Reserved
#define PIN_SHARE_PORTB_5						0

//0: SPI_CS#
//1: GPIOB[4]
//2~7: Reserved
#define PIN_SHARE_PORTB_4						0

//0: DDC0_SDA
//1: GPIOB[3]
//2: TCON8
//3: I2C_S_SDA
//4: V8_DATA0
//5: UART0_TX
//6: UART1_TX
//7: I2C_M1_SDA
#define PIN_SHARE_PORTB_3						0//5

//0: DDC0_SCL
//1: GPIOB[2]
//2: TCON9
//3: I2C_S_SCL
//4: V8_CLK
//5: UART0_RX
//6: UART1_RX
//7: I2C_M1_SCL
#define PIN_SHARE_PORTB_2						0//5

//0: DDC1_SDA
//1: GPIOB[1]
//2: UART0_TX
//3: UART1_TX
//4: TCON6
//5~7: Reserved
#define PIN_SHARE_PORTB_1						0

//0: DDC1_SCL
//1: GPIOB[0]
//2: UART0_RX
//3: UART1_RX
//4: TCON4
//5~7:Reserved
#define PIN_SHARE_PORTB_0						0

//#define PIN_SHARE_PORTC_7
//#define PIN_SHARE_PORTC_6

//0: HSYNCVIN0
// 1: GPIOC[5]
// 2~7:Reserved
// Remarks: 此pin當切成GPIO時，只當GPI使用
#define PIN_SHARE_PORTC_5						0

// 0: VSYNCVIN0
// 1: GPIOC[4]
// 2~7:Reserved
#define PIN_SHARE_PORTC_4						1
//Can tuner
//0: RF_AGC
// 1: GPIOC[3]
// 2. TCON10
// 3~7:Reserved
#define PIN_SHARE_PORTC_3						1

//0: IRRX
// 1: GPIOC[2]
// 2: TCON11
// 3: XTAL_OUT
// 4:V8_CLK
//5~7:Reserved
#define PIN_SHARE_PORTC_2						0

//0: I2C_M0_SCL
// 1: GPIOC[1]
// 2. TCON12
// 3:Reserved
// 4: UART0_TX
//5: I2C_S_SCL
//6~7:Reserved
#define PIN_SHARE_PORTC_1						0

//0: I2C_M0_SDA
//1: GPIOC[0]
//2. TCON13
//3:Reserved
//4: UART0_RX
//5: I2C_S_SDA
//6~7:Reserved
#define PIN_SHARE_PORTC_0						0
#if 1//(CONFIG_DISPLAY_PANEL_STYLE == _PANEL_INTERFACE_TTL)

#define PIN_SHARE_PORTD_1						3//0: TECLKN//1: GPIOD[1].//2: B_G2N//3: TTL_GRN44~7:Reserved
#define PIN_SHARE_PORTD_0						3//0: TECLKP// 1: GPIOD[0]// 2. B_G2P// 3: TTL_GRN5//4~7:Reserved

//0: All LVDS pin be LVDS function except TECLKN and TECLKP
//1: Reserved
//2. All LVDS pin be RSDS function except TECLKN and TECLKP
//3: All LVDS pin be TTL function except TECLKN and TECLKP
//4~7:Reserved
#define PIN_SHARE_PORTD_2						3
#else
#define PIN_SHARE_PORTD_1						0//0: TECLKN//1: GPIOD[1].//2: B_G2N//3: TTL_GRN44~7:Reserved
#define PIN_SHARE_PORTD_0						0//0: TECLKP// 1: GPIOD[0]// 2. B_G2P// 3: TTL_GRN5//4~7:Reserved

//0: All LVDS pin be LVDS function except TECLKN and TECLKP
//1: Reserved
//2. All LVDS pin be RSDS function except TECLKN and TECLKP
//3: All LVDS pin be TTL function except TECLKN and TECLKP
//4~7:Reserved
#define PIN_SHARE_PORTD_2						0
#endif

//0: A_B2N
//1: GPIOG[7]
//2~7:Reserved
#define PIN_SHARE_PORTG_7						1

//0: A_B2P
//1: GPIOG[6]
//2~7:Reserved
#define PIN_SHARE_PORTG_6						1

//0: A_B1N
//1: GPIOG[5]
//2~7:Reserved
#define PIN_SHARE_PORTG_5						1

//0: A_B1P
//1: GPIOG[4]
//2~7:Reserved
#define PIN_SHARE_PORTG_4						1

//0: A_B0N
//1: GPIOG[3]
//2~7:Reserved
#define PIN_SHARE_PORTG_3						1

//0: A_B0P
//1: GPIOG[2]
//2~7:Reserved
#define PIN_SHARE_PORTG_2						1

//0: A_G2N
//1: GPIOG[1]
//2~7:Reserved
#define PIN_SHARE_PORTG_1						1

//0: A_G2P
//1: GPIOG[0]
//2~7:Reserved
#define PIN_SHARE_PORTG_0						1

//0: A_G1N
// 1: GPIOH[7]
// 2~7:Reserved
#define PIN_SHARE_PORTH_7						1

//0: A_G1P
//1: GPIOH[6]
//2~7:Reserved
#define PIN_SHARE_PORTH_6						1

//0: A_G0N
//1: GPIOH[5]
//2~7:Reserved
#define PIN_SHARE_PORTH_5						1

//0: A_G0P
//1: GPIOH[4]
//2~7:Reserved
#define PIN_SHARE_PORTH_4						1

//0: A_CLKN
//1: GPIOH[3]
//2~7:Reserved
#define PIN_SHARE_PORTH_3						1

//0: A_CLKP
//1: GPIOH[2]
//2~7:Reserved
#define PIN_SHARE_PORTH_2						1

//0: A_R2N
//1: GPIOH[1]
//2~7:Reserved
#define PIN_SHARE_PORTH_1						1

//0: A_R2P
//1: GPIOH[0]
//2~7:Reserved
#define PIN_SHARE_PORTH_0						1

//0: A_R1N
//1: GPIOI[7]
//2~7:Reserved
#define PIN_SHARE_PORTI_7						1

//0: A_R1P
//1: GPIOI[6]
//2~7:Reserved
#define PIN_SHARE_PORTI_6						1

//0: A_R0N
//1: GPIOI[5]
//2~7:Reserved
#define PIN_SHARE_PORTI_5						1

//0: A_R0P
//1: GPIOI[4]
//2~7:Reserved
#define PIN_SHARE_PORTI_4						1

// GPIO configuration
// De-bounce clock base.
#define GPIO_0_7_DEBOUNCE					GPIO_DEBOUNCE_CLOCK_37ns
#define GPIO_8_15_DEBOUNCE					GPIO_DEBOUNCE_CLOCK_37ns
#define GPIO_16_23_DEBOUNCE					GPIO_DEBOUNCE_CLOCK_37ns
#define GPIO_24_31_DEBOUNCE					GPIO_DEBOUNCE_CLOCK_37ns
#define GPIO_32_38_DEBOUNCE					GPIO_DEBOUNCE_CLOCK_37ns

//GPIO0
#define GPIO0_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO0_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO1
#define GPIO1_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO1_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO2
#define GPIO2_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO2_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO3
#define GPIO3_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO3_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO4
#define GPIO4_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO4_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO5
#define GPIO5_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO5_ACTICE_LEVEL						GPIO_ACTIVE_HIGH

//GPIO6
#define GPIO6_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO6_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO7
#define GPIO7_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO7_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO8
#define GPIO8_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO8_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO9
#define GPIO9_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO9_ACTICE_LEVEL						GPIO_ACTICE_LOW

//GPIO10
#define GPIO10_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO10_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO11
#define GPIO11_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO11_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO12
#define GPIO12_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO12_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO13
#define GPIO13_DIRECTION						GPIO_DIRECTION_INPUT_PIN
#define GPIO13_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO14
#define GPIO14_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO14_ACTICE_LEVEL					GPIO_ACTIVE_HIGH

//GPIO15
#define GPIO15_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO15_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO16
#define GPIO16_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO16_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO17
#define GPIO17_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO17_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO8
#define GPIO18_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO18_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO19
#define GPIO19_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO19_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO20
#define GPIO20_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO20_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO21
#define GPIO21_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO21_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO22
#define GPIO22_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO22_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO23
#define GPIO23_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO23_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO24
#define GPIO24_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO24_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO25
#define GPIO25_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO25_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO26
#define GPIO26_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO26_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO27
#define GPIO27_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO27_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO28
#define GPIO28_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO28_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO29
#define GPIO29_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO29_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO30
#define GPIO30_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO30_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO31
#define GPIO31_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO31_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO32
#define GPIO32_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO32_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO33
#define GPIO33_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO33_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO34
#define GPIO34_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO34_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO35
#define GPIO35_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO35_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO36
#define GPIO36_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO36_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO37
#define GPIO37_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO37_ACTICE_LEVEL					GPIO_ACTICE_LOW

//GPIO38
#define GPIO38_DIRECTION						GPIO_DIRECTION_OUTPUT_PIN
#define GPIO38_ACTICE_LEVEL					GPIO_ACTICE_LOW

#if 1 // added by weihao, and modify in future
// AGPO_LSADC0		-0
#define AGPO_LSADC0_ENABLE_INPUT				_DISABLE
#define AGPO_LSADC0_ENABLE_OUTPUT			_DISABLE

// AGPO_LSADC1		-1
#define AGPO_LSADC1_ENABLE_INPUT				_ENABLE
#define AGPO_LSADC1_ENABLE_OUTPUT			_DISABLE

// AGPO_LSADC2		-2
#define AGPO_LSADC2_ENABLE_INPUT				_DISABLE//_ENABLE
#define AGPO_LSADC2_ENABLE_OUTPUT			   _DISABLE//_ENABLE

// AGPO_LSADC3		-3
#define AGPO_LSADC3_ENABLE_INPUT				_DISABLE
#define AGPO_LSADC3_ENABLE_OUTPUT			   _DISABLE

//AGPIO_AIO_1L		-4
#define AGPO_AIO_2L_ENABLE_INPUT				_DISABLE
#define AGPO_AIO_2L_ENABLE_OUTPUT			_ENABLE

//AGPO_AIO_1R		-5
#define AGPO_AIO_2R_ENABLE_INPUT				_DISABLE
#define AGPO_AIO_2R_ENABLE_OUTPUT			_ENABLE

// AGPO_VIN00P		-6
#define AGPO_VIN00P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN00P_ENABLE_OUTPUT			_DISABLE

// AGPO_VIN10P		-7
#define AGPO_VIN10P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN10P_ENABLE_OUTPUT			_ENABLE

// AGPO_VIN01P		-8
#define AGPO_VIN01P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN01P_ENABLE_OUTPUT			_DISABLE

// AGPO_VIN11P		-9
#define AGPO_VIN11P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN11P_ENABLE_OUTPUT			_DISABLE

// AGPO_VIN0N		-10
#define AGPO_VIN0N_ENABLE_INPUT				_DISABLE
#define AGPO_VIN0N_ENABLE_OUTPUT				_DISABLE

// AGPO_VIN02P		-11
#define AGPO_VIN02P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN02P_ENABLE_OUTPUT			_DISABLE

// AGPO_VIN12P		-12
#define AGPO_VIN12P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN12P_ENABLE_OUTPUT			_DISABLE

// AGPO_VIN02P		-13
#define AGPO_VIN1N_ENABLE_INPUT				_DISABLE
#define AGPO_VIN1N_ENABLE_OUTPUT				_DISABLE

// AGPO_VIN03P		-14
#define AGPO_VIN03P_ENABLE_INPUT				_DISABLE
#define AGPO_VIN03P_ENABLE_OUTPUT			_ENABLE

// AGPO_RGBSW0		-15
#define AGPO_RGBSW0_ENABLE_INPUT				_DISABLE
#define AGPO_RGBSW0_ENABLE_OUTPUT			_ENABLE

// AGPO_AIN_2L		-16
#define AGPO_AIN_2L_ENABLE_INPUT				_DISABLE
#define AGPO_AIN_2L_ENABLE_OUTPUT			_DISABLE

// AGPO_RGBSW1		-17
#define AGPO_RGBSW1_ENABLE_INPUT				_DISABLE
#define AGPO_RGBSW1_ENABLE_OUTPUT			_ENABLE

// AGPO_AIN_2R		-18
#define AGPO_AIN_2R_ENABLE_INPUT				_DISABLE
#define AGPO_AIN_2R_ENABLE_OUTPUT			_DISABLE

// AGPO_AVOUT2		-29
#define AGPO_AVOUT2_ENABLE_INPUT				_DISABLE
#define AGPO_AVOUT2_ENABLE_OUTPUT			_DISABLE

// AGPO_B2N			-20
#define AGPO_B2N_ENABLE_INPUT					_DISABLE
#define AGPO_B2N_ENABLE_OUTPUT				_DISABLE

// AGPO_B2P			-21
#define AGPO_B2P_ENABLE_INPUT					_DISABLE
#define AGPO_B2P_ENABLE_OUTPUT				_DISABLE

// AGPO_G2N			-22
#define AGPO_G2N_ENABLE_INPUT					_DISABLE
#define AGPO_G2N_ENABLE_OUTPUT				_DISABLE

// AGPO_G2P			-23
#define AGPO_G2P_ENABLE_INPUT					_DISABLE
#define AGPO_G2P_ENABLE_OUTPUT				_DISABLE

// AGPO_R2N			-24
#define AGPO_R2N_ENABLE_INPUT					_DISABLE
#define AGPO_R2N_ENABLE_OUTPUT				_DISABLE

// AGPO_R2P			-25
#define AGPO_R2P_ENABLE_INPUT					_DISABLE
#define AGPO_R2P_ENABLE_OUTPUT				_DISABLE

// AGPO_AIN_5L  		-26
#define AGPO_AIN_5L_ENABLE_INPUT				_DISABLE
#define AGPO_AIN_5L_ENABLE_OUTPUT			_DISABLE

// AGPO_AIN_5R  		-27
#define AGPO_AIN_5R_ENABLE_INPUT				_DISABLE
#define AGPO_AIN_5R_ENABLE_OUTPUT			_DISABLE

#else
// AGPO_LSADC0	-0
#define AGPO_LSADC0_ENABLE					_DISABLE

// AGPO_LSADC1	-1
#define AGPO_LSADC1_ENABLE					_DISABLE

// AGPO_LSADC2	-2
#define AGPO_LSADC2_ENABLE					_DISABLE

// AGPO_LSADC3	-3
#define AGPO_LSADC3_ENABLE					_DISABLE

// AGPO_AIO_2L	-4
#define AGPO_AIO_2L_ENABLE						_DISABLE

// AGPO_AIO_2R	-5
#define AGPO_AIO_2R_ENABLE					_ENABLE

// AGPO_VIN00P	-6
#define AGPO_VIN00P_ENABLE						_DISABLE

// AGPO_VIN10P	-7
#define AGPO_VIN10P_ENABLE						_ENABLE

// AGPO_VIN01P	-8
#define AGPO_VIN01P_ENABLE						_DISABLE

// AGPO_VIN11P	-9
#define AGPO_VIN11P_ENABLE						_DISABLE

// AGPO_VIN02P	-10
#define AGPO_VIN02P_ENABLE						_DISABLE

// AGPO_VIN12P	-11
#define AGPO_VIN12P_ENABLE						_DISABLE

// AGPO_VIN03P	-12
#define AGPO_VIN03P_ENABLE						_DISABLE

// AGPO_RGBSW0	-13
#define AGPO_RGBSW0_ENABLE					_DISABLE

// AGPO_AIN_2L	-14
#define AGPO_AIN_2L_ENABLE						_DISABLE

// AGPO_RGBSW1	-15
#define AGPO_RGBSW1_ENABLE					_DISABLE

// AGPO_AIN_2R	-16
#define AGPO_AIN_2R_ENABLE					_DISABLE

// AGPO_AVOUT2	-17
#define AGPO_AVOUT2_ENABLE					_DISABLE

// AGPO_AIN_5L	-18
#define AGPO_AIN_5L_ENABLE						_DISABLE

// AGPO_AIN_5R	-19
#define AGPO_AIN_5R_ENABLE					_DISABLE
#endif

// PWM
#define PWM0_ENABLE			_DISABLE
#define PWM0_GPIO				GPIO_A1//GPIO_C3//GPIO_A4
#define PWM0_SourceDivisor		0x2
#define PWM0_OutputDivisor		0xff

#define PWM1_ENABLE			_DISABLE
#define PWM1_GPIO				GPIO_A1
#define PWM1_SourceDivisor		0x2
#define PWM1_OutputDivisor		0x1

#define PWM2_ENABLE			_DISABLE
#define PWM2_GPIO				GPIO_A1
#define PWM2_SourceDivisor		0x2
#define PWM2_OutputDivisor		0x1

#define PWM3_ENABLE			_DISABLE
#define PWM3_GPIO				GPIO_A1
#define PWM3_SourceDivisor		0x2
#define PWM3_OutputDivisor		0x1

#define PWM4_ENABLE			_DISABLE
#define PWM4_GPIO				GPIO_A1
#define PWM4_SourceDivisor		0x2
#define PWM4_OutputDivisor		0x1

#define PWM5_ENABLE			_DISABLE
#define PWM5_GPIO				GPIO_A1
#define PWM5_SourceDivisor		0x2
#define PWM5_OutputDivisor		0x1

#define UART_USE_UART0			0
#define UART_USE_UART1			1
#define UART_MONITOR_SOURCE				UART_USE_UART0

// UART
// Set options for UART0
#define UART_SOURCE_0_ENABLE				_ENABLE
#define UART_SOURCE_0_BAUDRATE			UART_BAUDRATE_115200
#define UART_SOURCE_0_PARITY_SELECT		UART_PARITY_SELECT_ODD
#define UART_SOURCE_0_PARITY_ENABLE		UART_PARITY_DISABLE
#define UART_SOURCE_0_STOP_BITS			UART_STOP_BITS_1
#define UART_SOURCE_0_DATA_BITS			UART_DATA_BITS_8

// Set options for UART1
#define UART_SOURCE_1_ENABLE				_DISABLE
#define UART_SOURCE_1_BAUDRATE			UART_BAUDRATE_115200
#define UART_SOURCE_1_PARITY_SELECT		UART_PARITY_SELECT_ODD
#define UART_SOURCE_1_PARITY_ENABLE		UART_PARITY_DISABLE
#define UART_SOURCE_1_STOP_BITS			UART_STOP_BITS_1
#define UART_SOURCE_1_DATA_BITS			UART_DATA_BITS_8

// LSADC
// Pad lsadc global configuration
#define PAD_LSADC_OPAMP_SETTLING_TIME	0x01
#define PAD_LSADC_ADC_CLOCK_RATE			0x06
#define PAD_LSADC_DEBOUNCE_COUNT		0x00

// PAD 0
#define PAD_LSADC_ENABLE_0				_ENABLE
#define PAD_LSADC_MODE_CONTROL_0 	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_0			0
#define PAD_LSADC_CURRENT_0			0
#define PAD_LSADC_SWITCH_0			PAD_LSADC_SWITCH_PIN_0

// PAD 1
#define PAD_LSADC_ENABLE_1				_DISABLE
#define PAD_LSADC_MODE_CONTROL_1	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_1			0
#define PAD_LSADC_CURRENT_1			0
#define PAD_LSADC_SWITCH_1			PAD_LSADC_SWITCH_PIN_1

// PAD 2
#define PAD_LSADC_ENABLE_2				_DISABLE
#define PAD_LSADC_MODE_CONTROL_2	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_2			0
#define PAD_LSADC_CURRENT_2			0
#define PAD_LSADC_SWITCH_2			PAD_LSADC_SWITCH_PIN_2

// PAD 3
#define PAD_LSADC_ENABLE_3				_DISABLE
#define PAD_LSADC_MODE_CONTROL_3	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_3			0
#define PAD_LSADC_CURRENT_3			0
#define PAD_LSADC_SWITCH_3			PAD_LSADC_SWITCH_PIN_3

// PAD 4
#define PAD_LSADC_ENABLE_4				_DISABLE
#define PAD_LSADC_MODE_CONTROL_4	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_4			0
#define PAD_LSADC_CURRENT_4			0
#define PAD_LSADC_SWITCH_4			PAD_LSADC_SWITCH_PIN_4

// PAD 5
#define PAD_LSADC_ENABLE_5				_DISABLE
#define PAD_LSADC_MODE_CONTROL_5	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_5			0
#define PAD_LSADC_CURRENT_5			0
#define PAD_LSADC_SWITCH_5			PAD_LSADC_SWITCH_PIN_5

// PAD 6
#define PAD_LSADC_ENABLE_6				_DISABLE
#define PAD_LSADC_MODE_CONTROL_6	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_6			0
#define PAD_LSADC_CURRENT_6			0
#define PAD_LSADC_SWITCH_6			PAD_LSADC_SWITCH_PIN_6

// PAD 7
#define PAD_LSADC_ENABLE_7				_DISABLE
#define PAD_LSADC_MODE_CONTROL_7	PAD_LSADC_VOLTAGE_MODE
#define PAD_LSADC_THRESHOLD_7			0
#define PAD_LSADC_CURRENT_7			0
#define PAD_LSADC_SWITCH_7			PAD_LSADC_SWITCH_PIN_7

// Timer
#define TIMER_ENABLE_0					_ENABLE
#define TIMER_TARGET_0					 270000	// 10msec
#define TIMER_DIVIDER_0				0

#define TIMER_ENABLE_1					_ENABLE
#define TIMER_TARGET_1					240000	// 10msec
#define TIMER_DIVIDER_1				0

#define TIMER_ENABLE_2					_ENABLE
#define TIMER_TARGET_2					0xffffffff
#define TIMER_DIVIDER_2				0xa8

// Set GPIO number for specified purpose
//#define GPIO_AUDIO_AMP_MUTE				AGPO_RGBSW1
//#define GPIO_LED_RED						AGPO_RGBSW0
//#define GPIO_LED_GREEN						AGPO_VIN03P//GPIO14

#define GPIO_IR_CH						AGPO_RGBSW0
#define GPIO_IR_EN						AGPO_VIN03P//GPIO14

//#define GPIO_ISDB_POWER_ENABLE			AGPO_VIN10P
#define GPIO_SEL_A			            AGPO_VIN10P
#define GPIO_SEL_B			            GPIO_A6

//#define GPIO_PVR_SWITCH_ENABLE			GPIO12
//#define GPIO_AV_PVR_SEL					GPIO10
//#define GPIO_YPBPR_SELECT					GPIO_A1
#define ADC0_MUX_YPBPR					0
#define ADC0_MUX_SCART_RGB				1

//#define GPIO_STB_CTRL					AGPO_LSADC3

#define GPIO_BACKLIGHT_POWER_ENABLE		GPIO_A7
#define GPIO_PANEL_POWER_ENABLE			AGPO_RGBSW1//AGPO_AIO_2L
#define GPIO_HDMI0_HOT_PLUG				AGPO_AIO_2R
#define GPIO_HDMI1_HOT_PLUG				AGPO_AIO_2R
#define GPIO_BLACK_PWM					GPIO_A4
#define GPIO_POWER_KEY					AGPO_LSADC1

#define GPIO_POWER_ON					AGPO_AIO_2L	

#define GPIO_DVD_SW					    AGPO_RGBSW1
#if CONFIG_USB_CHECK
#define GPIO_LOADING_CTRL			   	 GPIO_C3
#define GPIO_MUTE				        GPIO_A4

#endif
//#define GPIO_DISCIN_CTRL			    AGPO_LSADC2


//#define ADC_EARPHONE                    AGPO_LSADC2


// Set GPIO number for specified purpose
#define GPIO_SCART1_FUNCTION_SELECT		PAD_LSADC_2
#define GPIO_SCART2_FUNCTION_SELECT		PAD_LSADC_3

#define GPIO_KEY_PAD1						PAD_LSADC_1
#define GPIO_KEY_PAD0						PAD_LSADC_0

// Set PWM
#define GPIO_PWM_BACKLIGH					PWM_0

// I2C mater for Tuner
#define I2C_MASTER_TUNER 					CHIP_I2C1
#ifdef CONFIG_TUNER_SILICON
 #define I2C_MASTER_TUNER_ADDR			0x3a
#else
#define I2C_MASTER_TUNER_ADDR			0x60
#endif

#define GPIO_DTV_IR_SEND			    GPIO_A5
#if CONFIG_ENABLE_USB
#define GPIO_IR_SEND				    GPIO_A6
#endif

//#define GPIO_BACK_IO					GPIO_A6

#define _MAX_SOURCE_INDEX		(_SOURCE_INDEX_NUM-1)
enum UI_SOURCE_INDEX
{
    //Tim 0325
#if 0
	    _SOURCE_INDEX_VGA,
	#ifdef CONFIG_ENABLE_HDMI
	    _SOURCE_INDEX_HDMI0,
	#endif
	//	_SOURCE_INDEX_HDMI1,
	#ifdef _VIDEO_TV_SUPPORT
	    _SOURCE_INDEX_TV,
	#endif
	    _SOURCE_INDEX_AV,
	    _SOURCE_INDEX_AV_1,
	    _SOURCE_INDEX_SV,
	    _SOURCE_INDEX_YPBPR,
	#ifdef CONFIG_SCART_AUTO_SWITCH
	    _SOURCE_INDEX_SCART_0,
	    _SOURCE_INDEX_SCART_1,
	#endif
	    _SOURCE_INDEX_NUM,

#else

	#ifdef _VIDEO_TV_SUPPORT
        _SOURCE_INDEX_TV,
	#endif
	
   	_SOURCE_INDEX_AV,
    _SOURCE_INDEX_AV_1,
    _SOURCE_INDEX_AV_2,
	_SOURCE_INDEX_AV_3,
    _SOURCE_INDEX_SV,
    _SOURCE_INDEX_YPBPR,
    #if CONFIG_ENABLE_USB
	_SOURCE_INDEX_USB,
	#endif
    _SOURCE_INDEX_VGA,
#ifdef CONFIG_ENABLE_HDMI
    _SOURCE_INDEX_HDMI0,
#endif


   
#ifdef CONFIG_SCART_AUTO_SWITCH
    _SOURCE_INDEX_SCART_0,
    _SOURCE_INDEX_SCART_1,
#endif
    _SOURCE_INDEX_NUM,
#endif
};


#endif // #ifndef _PCB_CUSTOMER_H
